### PR TITLE
Fix signurl to support path-style bucket access via check_bucket_name_dns_support

### PR DESCRIPTION
**Pull request by zmedico**
When check_bucket_name_dns_support returns False, format the url
for path-style bucket access (related to https://github.com/s3tools/s3cmd/pull/416).

### CODE REVIEW

**Comment by fghaas** [comment]
I'm also being bitten by this issue. @fviard, would you consider merging this PR?

**Comment by fghaas** [comment]
Hi @fviard — I'm taking the liberty to bring this up again, 3 months on. Would you consider merging this?

**Comment by fghaas** [comment]
@fviard Could this be merged, please? It's been almost a year since this was submitted.

**Comment by fviard** [comment]
Merged! Thank you and sorry for the very very long delay.

**Pull request merged**
