### PR TITLE
Configurable public URL protocol

### PR DESCRIPTION
**Pull request by junousi**
If public_url_use_https is true, prefix public URLs with https. Otherwise use
http as before.

### CODE REVIEW

**Comment by fviard** [comment]
Hi, thank you for your contribution.
The question come back regularly, but having https as a default public url is creating a lot of issues.
See: https://github.com/s3tools/s3cmd/issues/666
The https for connecting to aws s3, is not the same as the public link serve a content.

If you would be willing to rework your patch, I think that it would be good to finally fix this issue by creating a dedicated config option for that (but that can't be enabled by default)

**Comment by junousi** [comment]
Hi, sure thing!

I'm a bit unsure what to rework as public_url() seems to be mostly feeding output() or info() and not plugging into other s3cmd functionality, so would need a pointer for what else to change. In any case a simple config parameter separate from use_https is now amended.

**Comment by junousi** [comment]
Also some background. We're running an object storage service with CephRGW/S3 open to the world only over https/443, hence any form of configurability for changing the public URL prefix from http to https would be a plus.

**Comment by fviard** [comment]
Merged, thank you very much!

**Comment by fviard** [comment]
In fact I just realized that we had "signurl_use_https".
signurl and public_url are basically the same kind of thing and if someone might accept one, the other one is probably acceptable for him.
signurl_use_https would have been a bad name if it was acting on public_uri also.

So probably, the right config should have been something like "url_use_https", or "use_https_for_url" and be shared for the 2 usages. But it would be annoying to change the name of a config that is already there for a few years :-s

**Comment by junousi** [comment]
> But it would be annoying to change the name of a config that is already there for a few years :-s

Agreed. In time perhaps both parameters can be superseded with the common one, but I think it's better to do this small incremental change first. Cheers!

**Pull request merged**
