### PR TITLE
Fix Issue #672

### PR DESCRIPTION
**Pull request by MLopez-Ibanez**
With --follow-links, the target of symlinks should have the mime-type of the file they point to, not of the symlink. Dereference the link before guessing its mime-type.

### CODE REVIEW

**Comment by fviard** [comment]
Thanks for your PR, the idea is interesting.
Still I have 2 remarks:
1) Is it possible for your do a PR with a rebase instead of with a "merge" to have a clean history.
2) Is there any reason you think of to do the following test:
   if os.path.islink(deunicodise(filename)):
instead of just using "realpath" for all filenames?

**Comment by MLopez-Ibanez** [comment]
1) How do I do that from the command-line?
2) Not sure why I did it this. Perhaps I did not want to change the filename at all if it was not a symlink. But your proposal seems to work fine for my purposes.

**Comment by fviard** [comment]
Sorry for my reply after a very long time.
In your case, as the patch is short, it would probably be better to create a new clean branch from master and reply your patch on it.
Otherwise, for another future patch, use the following command to rebase based on master:
 git rebase upstream/master
(If we assume that upstream is the github s3cmd master)

**Comment by fviard** [comment]
I did a patch based on your proposal, and it is now in master:
https://github.com/s3tools/s3cmd/commit/d7b60b894b1d58d9dd66ea603d3438f0e576589b

Please give it a try and thank you for the initial PR.

**Pull request closed without merging**
