### PR TITLE
Bug/region endpoints

### PR DESCRIPTION
**Pull request by mdomsch**
Help for #402

### CODE REVIEW

**Comment by glaszig** [comment]
this really is a show stopper.

**Comment by mdomsch** [comment]
why is it a showstopper?  s3cmd works with all regions right now, it's not
not as efficient as it could be network-wise.

**Comment by glaszig** [comment]
with `--region=eu-central-1` i'm getting `Warning: Redirected to us-west-1`...

**Comment by vamitrou** [comment]
@glaszig If you **don't** issue a *create bucket* command then your output is expected.

Could you post the command you are trying?
If your bucket for example is in us-west-1 and you are trying to access it with --region=eu-central-1 it makes sense to redirect you in eu-central-1.

**Comment by glaszig** [comment]
the issue went away after commenting here. quite weird. i assume it was my fault. sorry and thanks.=

**Comment by fviard** [comment]
Obsolete PR. Issue is now already fixed in MASTER.

**Pull request closed without merging**
