### PR TITLE
Avoid distutils usage at runtime

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
This avoids the distutils need as runtime dependency

### CODE REVIEW

**Comment by fviard** [comment]
Thank you for the PR, in the theory i'm in favor to remove the dependency on distutils, but "which" is not available in python2 (2.6, 2.7) so I can't accept the PR as is or s3cmd would be broken for python 2.
Maybe, you can simply add a fallback to find_executable on ImportError ?

To be noted, but I don't know if there could be a chance that this affect an user, there is a subtle difference between find_package and which based on the following link:
https://stackoverflow.com/questions/9877462/is-there-a-python-equivalent-to-the-which-command
>  Keep in mind that unlike which, find_executable does not actually check that the result is marked as executable.

**Comment by LocutusOfBorg** [comment]
Hello!

>Thank you for the PR, in the theory i'm in favor to remove the dependency on distutils, but "which" is >not available in python2 (2.6, 2.7) so I can't accept the PR as is or s3cmd would be broken for python >2.

I see..
>Maybe, you can simply add a fallback to find_executable on ImportError ?

>To be noted, but I don't know if there could be a chance that this affect an user, but there is a subtle >difference between find_package and "which":

I would say that which is superior then :)

**Comment by LocutusOfBorg** [comment]
This should be better now...

**Comment by fviard** [comment]
Thank you.
I would probably look picky, but can you change it again to only have imports at the top of the file?
I think that it would be ok to import which as "find_executable" or the opposite to use a single call in the body itself.

**Comment by LocutusOfBorg** [comment]
Oh... it was so easy... I tried to remember a good way to do it, and now I got it! thanks for the help!

**Comment by fviard** [comment]
Perfect, merged, thank you!

**Pull request merged**
