### PR TITLE
Add getlifecycle command

### PR DESCRIPTION
**Pull request by dang**
Add a command to get lifecycle configuration from a bucket.

Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

We are implementing lifecycle in Ceph RadosGW and need this command.

### CODE REVIEW

**Comment by fviard** [comment]
@dang Thanks for the proposal, adding this would be nice, but please see my review comments of the following PR:
https://github.com/s3tools/s3cmd/pull/715

**Comment by dang** [comment]
Okay, I've updated with the comments from #715

**Comment by dang** [comment]
Bump

**Comment by fviard** [comment]
Merged, thank you very much for the work!

**Pull request merged**
