### PR TITLE
list-objects-*: implement allow unordered option

### PR DESCRIPTION
**Pull request by snosratiershad**
As discussed in [this issue](https://github.com/s3tools/s3cmd/issues/1269)

### CODE REVIEW

**Comment by snosratiershad** [comment]
@fviard, if there is anything I can help about it, feel free to contact me.

**Comment by fviard** [comment]
Sorry for the delay of my reply.  
Instead of adding the parameter to all the function prototypes, i think that you can use directly `self.config.allow_unordered` inside ` def bucket_list_noparse(...)`.

**Comment by snosratiershad** [comment]
@fviard, as you requested, I changed it to a config variable.
I couldn't found any of documentation files in the repository, but I think it must be included in somewhere as there is no help message for now.

**Comment by snosratiershad** [comment]
@fviard, should command line switch literally overwrite config file, or just ignoring the value comes from `self.config.list_objects_allow_unordered` when the `--ls-allow-unordered'  switch called?

**Comment by snosratiershad** [comment]
I realized what you mean. also going to change "list-objects-allow-unordered" to "list-allow-onordered".

**Comment by snosratiershad** [comment]
@fviard Done.

**Comment by fviard** [comment]
Merged, thank you!

**Comment by visbits** [comment]
Delimiter cannot be used with allow-unordered.

The code must not set a limiter if allow-unordered is true:
From line 400 in S3.py
`        if not self.config.recursive and not recursive:`
To
`        if not self.config.recursive and not recursive and not self.config.list_allow_unordered:`

**Comment by snosratiershad** [comment]
@visbits Thanks for pointing this out. I'll check it out and fix it.

**Pull request merged**
