### PR TITLE
Invalidate multiple CF distributions when necessary

### PR DESCRIPTION
**Pull request by jmif**
Add support for invalidating multiple CF distributions with  --cf-inval when the bucket is the origin for multiple distributions

### CODE REVIEW

**Comment by mdomsch** [comment]
I have never worked with CF.  Have you tested this? How extensively?  Can you add some tests to our test suite for CF?

Thanks,
Matt

**Comment by mdomsch** [comment]
See also #418

**Comment by jmif** [comment]
Quite extensively, use it in our production JS release pipeline every day.  Unfortunately wont have time to add tests to the codebase in the near future but I'll put in on my radar.

**Comment by fviard** [comment]
@jmif Thanks for your contribution, I'm also not very familiar with CF, but the logic of your patch looks good.
There is a single point that I can see in review, you should use the builtin "set" type instead of the imported "Set". As sets.Set is deprecated since python 2.6 (and we have decided that compatibility with previous versions of python is not needed).

**Comment by jmif** [comment]
Updated and did some light testing but haven't won't be able to test extensively for some time.  Thanks for reviewing.

**Comment by fviard** [comment]
Merged. Thank you and sorry for the delay.

**Pull request merged**
