### PR TITLE
Support for custom S3 api path

### PR DESCRIPTION
**Pull request by kwarunek**
This changes allows user to set path to S3 api instead of default '/'. It will enable s3cmd to work with s3ninja or custom s3-ceph endpoints.

### CODE REVIEW

**Comment by fviard** [comment]
@kwarunek Thank you for your proposal, it is nice to see that we can be compatible with a custom api_endpoint with a so small change.

But if you are willing to rework your patch, I think that it will be greater to support "api_endpoints" not by having a custom config key, but just by adding the api_endpoint to host_base / host_bucket.
Ex.: host_base = s3.myserver.com:2233/custom_endpoint_path/blurp/
Currently, we already deal with all the stripping necessary in "ConnMan".
There is probably not so much function to fix to support that.

**Comment by kwarunek** [comment]
ok, I'll work on it

**Comment by fviard** [comment]
That looks great for me.
Would you mind doing a rebase/squash to have a single commit based on master? otherwise I will have to manually merge it as there is a conflict.

**Comment by fviard** [comment]
Merged, thank you very much!

**Comment by kwarunek** [comment]
awesome, thanks

**Pull request merged**
