### PR TITLE
Use IMDSv2 to retrieve instance metadata

### PR DESCRIPTION
**Pull request by AnthonyFoiani-at**
# Summary

Hello!

We are trying to disable IMDSv1 across our fleet, to improve our security posture.

(Some background: an explanation of what AWS did, and why, is in [Add defense in depth against open firewalls, reverse proxies, and SSRF vulnerabilities with enhancements to the EC2 Instance Metadata Service](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/). They also provide a helpful article on how to [Use IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html).)

`s3cmd` had IMDSv1 hard-coded, so it failed on machines where we disabled this feature.

This PR is a (fairly minimal?) change to use IMDSv2. (It would probably be much cleaner to use the AWS-supported APIs, but I also appreciate that `s3cmd` is a nice standalone install!)

Some other folks have hit this problem:

* Gitlab Chart: [Cloud native backup does not support deployments in AWS with IMDSv1 disabled](https://gitlab.com/gitlab-org/charts/gitlab/-/issues/2787)

# Testing

With original code, on a machine with IMDSv1 disabled:

```
root@ip-172-20-137-224:/usr/local/lib/python2.7/dist-packages/S3# ln -s Config-orig.py Config.py
root@ip-172-20-137-224:/usr/local/lib/python2.7/dist-packages/S3# s3cmd help
ERROR: /root/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
```

With this fix:

```
root@ip-172-20-137-224:/usr/local/lib/python2.7/dist-packages/S3# ln -s Config-imdsv2.py Config.py
root@ip-172-20-137-224:/usr/local/lib/python2.7/dist-packages/S3# s3cmd help
ERROR: Invalid command: help
```

Please consider rolling this in to your tool. Thanks!

### CODE REVIEW

**Comment by fviard** [comment]
Thank you for the info and the PR.

"The AWS approach is to block open WAFs by using a type of request that open WAFs very rarely support, HTTP PUT requests."
I'm not really convinced by the added value of IMDSv2 compare to the burden, but indeed it is very good to add support for that to s3cmd.

Your change looks good also, but there is one remaining question to resolve before merging:
- Is there any s3 compatible service that would also offer IMDSv1 currently, doing the same thing as amazon, but that would not support IMDSv2 requests?
- If yes, how can we avoid breaking them and remain compatible? Maybe we should just ignore a failure to /latest/api/token, and only set "X-aws-ec2-metadata-token" if we successfully got one?

**Comment by AnthonyFoiani-at** [comment]
> Thank you for the info and the PR.

You're very welcome! Thank **you** for maintaining a great tool!

> Is there any s3 compatible service that would also offer IMDSv1 currently, doing the same thing as amazon, but that would not support IMDSv2 requests?

I think it's more than just s3 compatibility that would have to be present; it would be the deep structure of instance metadata and credentials.

I could see an S3 compatibility issue where the various credentials used by some otherwise-compatible-with-s3 service need to get set -- but I would expect the intersection of "emulates `ec2metadata` v1 correctly" and "doesn't support `ec2metadata` v2 properly" is pretty small. :-)

Regardless, your suggestion sounds good to me. Let me bake that in; worst case, we don't get a token, so we try without the token.

Hopefully can update the PR in a few minutes!

**Comment by AnthonyFoiani-at** [comment]
> Maybe we should just ignore a failure to /latest/api/token, and only set "X-aws-ec2-metadata-token" if we successfully got one?

Hopefully https://github.com/s3tools/s3cmd/pull/1255/commits/4b7ad6de7d276e4f380d7de25ca9a1fa8e7f04ff is close to what you had in mind?

A quick test with the same technique succeeded in the same way.

**Comment by fviard** [comment]
Merged, thank you!

**Comment by AnthonyFoiani-at** [comment]
Thank **you**!

**Pull request merged**
