### PR TITLE
Added support for listing StorageClass attribute.

### PR DESCRIPTION
**Pull request by BCrookAtRA**
Disabled by default.  Enable with list_storageclass = True in .s3cfg

### CODE REVIEW

**Comment by BCrookAtRA** [comment]
As requested yesterday on s3tools-general@lists.sourceforge.net, here is my pull request.

**Comment by mdomsch** [comment]
Thanks.  A couple things:

1) let's just call this "cfg.long_listing' so we have some flexibility to add additional content later.
2) can you add a "-l" command line option?  LIke this:
' optparser.add_option("-l", dest="list_storageclass", action="store_true", help="Produce long listing [ls]") '

3) I think the storage class should come after the size, and before the object name.

Thanks,
Matt

**Comment by BCrookAtRA** [comment]
How's it looking now?  (I assumed you'd want dest=long_listing in your optparser example.)

**Comment by BCrookAtRA** [comment]
@mdomsch Is there anything you'd like to see me write differently/better?

**Comment by mdomsch** [comment]
Merged, thanks!

**Pull request closed without merging**
