### PR TITLE
Support bucket/object tagging command

### LINKED ISSUE #911: Add object tagging feature
Would be very useful during `put`, `sync`, etc..

http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

### PR DESCRIPTION
**Pull request by jeffwang0516**
Support Put/Get/DeleteBucketTagging & Put/Get/DeleteObjectTagging ( resolve #911 )

AWS Spec Ref
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketTagging.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html

### CODE REVIEW

**Comment by fviard** [comment]
Looks nice, thank you.
I will try to review that fast!

**Comment by fviard** [comment]
So, after looking at this, I think that it would be nice to be able to directly take the "tag" values for `settagging` and have a pretty print for `gettagging` instead of having xml input/outputs.

Here the xml is kind of just the request content, but there is no complex logic or customization that could request to expose that to the user.

What I would think would be something like that:
`s3cmd settagging s3://mybucket/myfile "MyFirstTag=value1&OtherKey=value2"

```
s3cmd gettagging s3://mybucket/myfile
s3://mybucket/myfile (object):
     MyfirstTag: value1
     OtherKey: value2
```

The & is mostly not used for tags, so could be an ok separator I think, but it requires to use quotes otherwise "the shell" might interpret it. And I'm thinking better to not separate by space as different argument each tag, because it might be good, in the future, to allow to have multiple files set in one time.

What do you think about that?

(btw the way, not for now, but for the future, I'm thinking about adding --iformat  and --oformat flags to be able to specify different formats for input or outputs.
for example, for input: "inline, xml", for output: "pretty,xml,csv,json".

**Comment by jeffwang0516** [comment]
@fviard It looks better! I've updated the code.

**Comment by fviard** [comment]
Finally merged. Sorry for the delay and thank you for the feature :-)

**Pull request merged**
